version: "3.9"

services:

  frontend:
    build: ./frontend
    container_name: chat_frontend
    ports:
      - "8080:80"
    networks:
      - chatnet

  backend:
    build: ./backend
    container_name: chat_backend
    ports:
      - "3000:3000"
    environment:
      GIGACHAT_CLIENT_ID: "019aded7-891b-75d4-a367-b24b68f34340"
      GIGACHAT_CLIENT_SECRET: "03aff5fd-6508-463d-ad2a-ea44edfb95c7"
    volumes:
      - ./backend/cert:/app/cert
    networks:
      - chatnet

networks:
  chatnet:
    driver: bridge